services:
  postgres:
    image: postgres:15
    container_name: fowlgen_db
    environment:
      POSTGRES_USER: fowlgen
      POSTGRES_PASSWORD: fowlgen_password
      POSTGRES_DB: fowlgenwars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fowlgen_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fowlgen_server
    depends_on:
      - postgres
    ports:
      - "7770:7770/udp"
      - "7770:7770/tcp"
    restart: unless-stopped

volumes:
  postgres_data:
