$path = "D:\Dev\TripoSR_Inputs"
$map = @{
    "asset_1.png" = "folhagem_verde_esfera.png"
    "asset_2.png" = "pedra_clara_rachada_esfera.png"
    "asset_3.png" = "pedras_terracota_esfera.png"
    "asset_4.png" = "metal_paineis_esfera.png"
    "asset_5.png" = "metal_liso_esfera.png"
    "asset_6.png" = "agua_azul_esfera.png"
    "asset_7.png" = "pedra_escura_rachada_esfera.png"
    "asset_8.png" = "cristal_verde_esfera.png"
    "asset_9.png" = "barril_madeira_esfera.png"
    "asset_10.png" = "pedra_cinza_esfera.png"
    "asset_11.png" = "terra_marrom_esfera.png"
    "asset_12.png" = "cachoeira_pedra.png"
    "asset_13.png" = "bloco_terra_grama_quina.png"
    "asset_14.png" = "arbusto_flores.png"
    "asset_15.png" = "cogumelos_azuis.png"
    "asset_16.png" = "muro_pedra.png"
    "asset_17.png" = "penhasco_agua.png"
    "asset_18.png" = "blocos_madeira.png"
    "asset_19.png" = "arbusto_verde.png"
    "asset_20.png" = "torre_pedra_bandeira_azul.png"
    "asset_21.png" = "torre_pedra_bandeira_vermelha.png"
    "asset_22.png" = "pinheiro.png"
    "asset_23.png" = "estatua_galinha_azul.png"
    "asset_24.png" = "estatua_galinha_vermelha.png"
    "asset_25.png" = "chao_pedra_circular.png"
    "asset_26.png" = "base_galinha_azul.png"
    "asset_27.png" = "base_galinha_vermelha.png"
    "asset_28.png" = "ponte_madeira_curva_1.png"
    "asset_29.png" = "ponte_madeira_curva_2.png"
    "asset_30.png" = "bloco_agua.png"
    "asset_31.png" = "bloco_grama_flores.png"
    "asset_32.png" = "bloco_pedra_musgo.png"
    "asset_33.png" = "bloco_grama_simples.png"
    "asset_34.png" = "chama_vermelha.png"
    "asset_35.png" = "chama_azul.png"
    "asset_36.png" = "cenario_fundo_montanhas.png"
    "asset_37.png" = "galinha_azul.png"
    "asset_38.png" = "galinha_vermelha.png"
    "asset_39.png" = "pedras_cinzas.png"
    "asset_40.png" = "ponte_madeira_reta.png"
    "asset_41.png" = "topo_estatua_galinha_esculpida.png"
    "asset_42.png" = "topo_estatua_galinha_vermelha.png"
    "asset_43.png" = "torre_pedra_bandeira_vermelha_2.png"
    "asset_44.png" = "vala_agua_pedra.png"
    "asset_45.png" = "caminho_pedra.png"
    "asset_46.png" = "bloco_terra_grama_alto.png"
    "asset_47.png" = "bloco_terra_grama_baixo.png"
    "asset_48.png" = "grupo_pinheiros.png"
    "asset_49.png" = "grupo_pinheiros_arbusto.png"
    "asset_50.png" = "mapa_completo_moba_galinhas.png"
}

foreach ($key in $map.Keys) {
    $oldFile = Join-Path $path $key
    $newFile = Join-Path $path $map[$key]
    if (Test-Path $oldFile) {
        Rename-Item -Path $oldFile -NewName $map[$key]
        Write-Host "Renamed $key to $($map[$key])"
    }
}
