apiVersion: v1
kind: Service
metadata:
  name: fishnet-server-service
spec:
  type: NodePort
  selector:
    app: fishnet-server
  ports:
    - name: fishnet-udp
      protocol: UDP
      port: 7770
      targetPort: 7770
      nodePort: 30770 # Porta fixa para acessar via IP do Minikube
    - name: fishnet-tcp
      protocol: TCP
      port: 7770
      targetPort: 7770
      nodePort: 30771
